name = "Hugo NexT"
license = "MIT"
licenselink = "https://github.com/hugo-next/hugo-theme-next/blob/main/LICENSE"
description = "Easily & powerful theme for Hugo engine."
homepage = "https://github.com/hugo-next/hugo-theme-next"
tags = ["Blog", "Simple", "Personal", "Responsive", "Documentation", "Light", "Dark"]
features = ["Blog", "Responsive", "Documentation", "Light", "Dark"]
min_version = "0.89.0"
demosite = "https://preview.hugo-next.eu.org"

[author]
  name = "lisenhui"
  homepage = "https://lisenhui.cn"
